# Generated by Django 3.2.7 on 2021-09-11 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('website', '0002_auto_20210911_1754'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndustryData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_industry', models.CharField(
                    choices=[('Technology & Telecom 1', 'Option 1'), ('Food & Beverages', 'Option 2'),
                             ('Travel & Leisure', 'Option 2'), ('Restaurants & Hotels', 'Option 2'),
                             ('Automotive', 'Option 2'), ('Apparel', 'Option 2'), ('Banking & Insurance', 'Option 2'),
                             ('Chain stores', 'Option 2'), ('Alcohol', 'Option 2'), ('Tobacco', 'Option 2'),
                             ('Business Services & consultancies', 'Option 2'), ('Transportation', 'Option 2'),
                             ('Media', 'Option 2'), ('Heavy equipments', 'Option 2')], max_length=100)),
                ('target_product', models.CharField(max_length=100)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.user')),
            ],
        ),
        migrations.AlterField(
            model_name='sentences',
            name='adjective',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sentences',
            name='object',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sentences',
            name='sentence',
            field=models.TextField(max_length=400),
        ),
        migrations.AlterField(
            model_name='sentences',
            name='subject',
            field=models.CharField(
                choices=[('Livinglab', 'Option 1'), ('Innovation', 'Option 1'), ('User experience', 'Option 1'),
                         ('Storytelling', 'Option 1'), ('Consumer Behaviour', 'Option 1'),
                         ('Behavioral economics', 'Option 1'), ('Consumer Insights', 'Option 1'),
                         ('Statistics', 'Option 1')], max_length=100),
        ),
        migrations.AlterField(
            model_name='sentences',
            name='verb',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='UserData',
        ),
    ]
