# Generated by Django 3.2.7 on 2021-09-14 11:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('website', '0004_auto_20210913_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentences',
            name='object_adjective',
            field=models.CharField(choices=[('-', ''), ('the', 'the'), ('a', 'a'), ('an', 'an')], default=('-', ''),
                                   max_length=100),
        ),
        migrations.AddField(
            model_name='sentences',
            name='subject_adjective',
            field=models.CharField(choices=[('-', ''), ('the', 'the'), ('a', 'a'), ('an', 'an')], default=('-', ''),
                                   max_length=100),
        ),
    ]
