# Generated by Django 3.2.7 on 2021-09-15 10:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('website', '0005_auto_20210914_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentences',
            name='modal_verb',
            field=models.CharField(
                choices=[('-none-', '-none-'), ('can', 'can'), ('may', 'may'), ('must', 'must'), ('ought', 'ought'),
                         ('shall', 'shall'), ('should', 'should'), ('would', 'would')], default='were', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sentences',
            name='negated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sentences',
            name='passive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sentences',
            name='perfect',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sentences',
            name='progressive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sentences',
            name='sentence_art',
            field=models.CharField(
                choices=[('Declarative', 'Declarative'), ('Yes-no', 'Yes-no'), ('What(object)', 'What(object)'),
                         ('Who(subject)', 'Who(subject)')], default='were', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sentences',
            name='tense',
            field=models.CharField(default='were', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sentences',
            name='object_adjective',
            field=models.CharField(choices=[('-', ''), ('the', 'the'), ('a', 'a'), ('an', 'an')], max_length=100),
        ),
        migrations.AlterField(
            model_name='sentences',
            name='subject_adjective',
            field=models.CharField(choices=[('-', ''), ('the', 'the'), ('a', 'a'), ('an', 'an')], max_length=100),
        ),
    ]
