# Generated by Django 3.2.7 on 2021-09-15 10:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('website', '0006_auto_20210915_1306'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sentences',
            old_name='object_adjective',
            new_name='object_determinant',
        ),
        migrations.RenameField(
            model_name='sentences',
            old_name='subject_adjective',
            new_name='subject_determinant',
        ),
    ]
