# Generated by Django 3.2.7 on 2021-09-15 10:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('website', '0007_auto_20210915_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentences',
            name='object_number',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sentences',
            name='subject_number',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
