# Generated by Django 3.2.7 on 2021-09-15 10:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('website', '0008_auto_20210915_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentences',
            name='tense',
            field=models.CharField(choices=[('Pr', 'Present'), ('Pa', 'Past'), ('F', 'Future')], max_length=100),
        ),
    ]
