# Generated by Django 3.2.7 on 2021-09-15 11:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('website', '0009_alter_sentences_tense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentences',
            name='tense',
            field=models.CharField(choices=[('Pr', 'Present'), ('Pa', 'Past'), ('F', 'Future')], default='Pr',
                                   max_length=100),
        ),
    ]
