# Generated by Django 3.2.7 on 2021-09-15 11:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('website', '0010_alter_sentences_tense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentences',
            name='modal_verb',
            field=models.CharField(
                choices=[('-none-', '-none-'), ('can', 'can'), ('may', 'may'), ('must', 'must'), ('ought', 'ought'),
                         ('shall', 'shall'), ('should', 'should'), ('would', 'would')], default='-none-',
                max_length=100),
        ),
        migrations.AlterField(
            model_name='sentences',
            name='object_determinant',
            field=models.CharField(choices=[('-', ''), ('the', 'the'), ('a', 'a'), ('an', 'an')], default='-',
                                   max_length=100),
        ),
        migrations.AlterField(
            model_name='sentences',
            name='sentence_art',
            field=models.CharField(
                choices=[('Declarative', 'Declarative'), ('Yes-no', 'Yes-no'), ('What(object)', 'What(object)'),
                         ('Who(subject)', 'Who(subject)')], default='Declarative', max_length=100),
        ),
        migrations.AlterField(
            model_name='sentences',
            name='subject',
            field=models.CharField(choices=[('Livinglab', 'Livinglab'), ('Innovation', 'Innovation'),
                                            ('User experience', 'User experience'), ('Storytelling', 'Storytelling'),
                                            ('Consumer Behaviour', 'Consumer Behaviour'),
                                            ('Behavioral economics', 'Behavioral economics'),
                                            ('Consumer Insights', 'Consumer Insights'), ('Statistics', 'Statistics')],
                                   default='Livinglab', max_length=100),
        ),
        migrations.AlterField(
            model_name='sentences',
            name='subject_determinant',
            field=models.CharField(choices=[('-', ''), ('the', 'the'), ('a', 'a'), ('an', 'an')], default='-',
                                   max_length=100),
        ),
    ]
