# Generated by Django 3.2.7 on 2021-09-16 13:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('website', '0011_auto_20210915_1410'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sentences',
            options={'verbose_name_plural': 'Sentences'},
        ),
        migrations.AlterField(
            model_name='sentences',
            name='tense',
            field=models.CharField(choices=[('present', 'present'), ('past', 'past'), ('future', 'future')],
                                   default='present', max_length=100),
        ),
    ]
