# Generated by Django 3.2.7 on 2021-09-22 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('website', '0012_auto_20210916_1600'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sentences',
            options={'verbose_name_plural': 'Sentence grammar'},
        ),
        migrations.RemoveField(
            model_name='sentences',
            name='sentence',
        ),
        migrations.CreateModel(
            name='SentenceResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('present', models.TextField(max_length=400)),
                ('past', models.TextField(max_length=400)),
                ('future', models.TextField(max_length=400)),
                ('progressive', models.TextField(max_length=400)),
                ('negated', models.TextField(max_length=400)),
                ('perfect', models.TextField(max_length=400)),
                ('passive', models.TextField(max_length=400)),
                ('sentence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.sentences')),
            ],
            options={
                'verbose_name_plural': 'Sentence results',
            },
        ),
    ]
