# Generated by Django 3.2.7 on 2021-09-22 11:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('website', '0013_auto_20210922_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentenceresults',
            name='future',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='sentenceresults',
            name='negated',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='sentenceresults',
            name='passive',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='sentenceresults',
            name='past',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='sentenceresults',
            name='perfect',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='sentenceresults',
            name='present',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='sentenceresults',
            name='progressive',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
    ]
