# Generated by Django 3.2.7 on 2021-09-22 23:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('website', '0014_auto_20210922_1416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sentences',
            name='modal_verb',
        ),
        migrations.RemoveField(
            model_name='sentences',
            name='negated',
        ),
        migrations.RemoveField(
            model_name='sentences',
            name='passive',
        ),
        migrations.RemoveField(
            model_name='sentences',
            name='perfect',
        ),
        migrations.RemoveField(
            model_name='sentences',
            name='progressive',
        ),
        migrations.RemoveField(
            model_name='sentences',
            name='sentence_art',
        ),
        migrations.RemoveField(
            model_name='sentences',
            name='tense',
        ),
        migrations.AddField(
            model_name='sentenceresults',
            name='modal_verb',
            field=models.CharField(
                choices=[('-none-', '-none-'), ('can', 'can'), ('may', 'may'), ('must', 'must'), ('ought', 'ought'),
                         ('shall', 'shall'), ('should', 'should'), ('would', 'would')], default='-none-',
                max_length=100),
        ),
    ]
