# Generated by Django 3.2.7 on 2021-09-23 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_auto_20210923_0215'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectedResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_sentence', models.CharField(max_length=200)),
                ('sentence_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.sentenceresults')),
            ],
        ),
    ]
