# Generated by Django 3.2.7 on 2021-09-27 09:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('website', '0016_selectedresult'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sentenceresults',
            old_name='sentence',
            new_name='sentence_grammar',
        ),
        migrations.RemoveField(
            model_name='sentenceresults',
            name='future',
        ),
        migrations.RemoveField(
            model_name='sentenceresults',
            name='negated',
        ),
        migrations.RemoveField(
            model_name='sentenceresults',
            name='passive',
        ),
        migrations.RemoveField(
            model_name='sentenceresults',
            name='past',
        ),
        migrations.RemoveField(
            model_name='sentenceresults',
            name='perfect',
        ),
        migrations.RemoveField(
            model_name='sentenceresults',
            name='present',
        ),
        migrations.RemoveField(
            model_name='sentenceresults',
            name='progressive',
        ),
    ]
