# Generated by Django 3.2.7 on 2021-09-27 11:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('website', '0017_auto_20210927_0931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sentenceresults',
            name='modal_verb',
        ),
        migrations.AddField(
            model_name='sentenceresults',
            name='sentence',
            field=models.TextField(default=django.utils.timezone.now, max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sentenceresults',
            name='sentence_type',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
