# Generated by Django 3.2.7 on 2021-09-29 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('website', '0020_alter_selectedresult_sentence_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentenceRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence_rank', models.IntegerField(default=0, max_length=2)),
                ('sentence_result',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.sentenceresults')),
            ],
        ),
        migrations.DeleteModel(
            name='SelectedResult',
        ),
    ]
