# Generated by Django 3.2.7 on 2021-09-29 10:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('website', '0021_auto_20210929_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentencerank',
            name='sentence_rank',
            field=models.IntegerField(default=0),
        ),
    ]
